import { Card } from "@/models/card/card";

export interface Bracket {
  gameChangers: boolean;
  maxGameChangers?: number;
  massLandDenial: boolean;
  extraTurns: boolean;
  chainingExtraTurns: boolean;
  twoCardInfinites: boolean;
  tutors: boolean;
  maxTutors?: number;
}

export enum BracketType {
  Exhibition = "Exhibition",
  Core = "Core",
  Upgraded = "Upgraded",
  Optimized = "Optimized",
  CEDH = "CEDH",
}

export enum BracketNumber {
  Exhibition = 1,
  Core = 2,
  Upgraded = 3,
  Optimized = 4,
  CEDH = 5,
}

export interface BracketDetails {
  bracket: BracketType;
  gameChangers: Card[];
  tutors: Card[];
  massLandDenial: Card[];
  extraTurns: Card[];
}

export const BaseBracketDetails: BracketDetails = {
  bracket: BracketType.Upgraded,
  gameChangers: [],
  tutors: [],
  massLandDenial: [],
  extraTurns: [],
};

export const Brackets: { [key: string]: Bracket } = {
  Exhibition: {
    gameChangers: false,
    massLandDenial: false,
    extraTurns: false,
    chainingExtraTurns: false,
    twoCardInfinites: false,
    tutors: true,
    maxTutors: 3,
  },
  Core: {
    gameChangers: false,
    massLandDenial: false,
    extraTurns: true,
    chainingExtraTurns: false,
    twoCardInfinites: false,
    tutors: true,
    maxTutors: 5,
  },
  Upgraded: {
    gameChangers: true,
    maxGameChangers: 3,
    massLandDenial: false,
    extraTurns: true,
    chainingExtraTurns: false,
    twoCardInfinites: false,
    tutors: true,
  },
  Optimized: {
    gameChangers: true,
    massLandDenial: true,
    extraTurns: true,
    chainingExtraTurns: true,
    twoCardInfinites: true,
    tutors: true,
  },
  CEDH: {
    gameChangers: true,
    massLandDenial: true,
    extraTurns: true,
    chainingExtraTurns: true,
    twoCardInfinites: true,
    tutors: true,
  },
};

export const GameChangers = [
  "Drannith Magistrate",
  "Enlightened Tutor",
  "Humility",
  "Serra's Sanctum",
  "Smothering Tithe",
  "Teferi's Protection",
  "Consecrated Sphinx",
  "Cyclonic Rift",
  "Expropriate",
  "Force of Will",
  "Fierce Guardianship",
  "Gifts Ungiven",
  "Intuition",
  "Jin-Gitaxias, Core Augur",
  "Mystical Tutor",
  "Narset, Parter of Veils",
  "Rhystic Study",
  "Sway of the Stars",
  "Thassa's Oracle",
  "Urza, Lord High Artificer",
  "Bolas's Citadel",
  "Braids, Cabal Minion",
  "Demonic Tutor",
  "Imperial Seal",
  "Necropotence",
  "Opposition Agent",
  "Orcish Bowmasters",
  "Tergrid, God of Fright",
  "Vampiric Tutor",
  "Ad Nauseam",
  "Deflecting Swat",
  "Gamble",
  "Jeska's Will",
  "Underworld Breach",
  "Crop Rotation",
  "Food Chain",
  "Gaea's Cradle",
  "Natural Order",
  "Seedborn Muse",
  "Survival of the Fittest",
  "Vorinclex, Voice of Hunger",
  "Worldly Tutor",
  "Aura Shards",
  "Coalition Victory",
  "Grand Arbiter Augustin IV",
  "Kinnan, Bonder Prodigy",
  "Yuriko, the Tiger's Shadow",
  "Notion Thief",
  "Winota, Joiner of Forces",
  "Ancient Tomb",
  "Chrome Mox",
  "Field of the Dead",
  "Glacial Chasm",
  "Grim Monolith",
  "Lion's Eye Diamond",
  "Mana Vault",
  "Mishra's Workshop",
  "Mox Diamond",
  "Panoptic Mirror",
  "The One Ring",
  "The Tabernacle at Pendrell Vale",
];

export const TutorSearch = `o:"search" and o:"your" and o:"library" and -o:"land" and -o:"basic" and -o:"plains" and -o:"island" and -o:"swamp" and -o:"forest" and -o:"mountain" and border:"black"`;

export const Tutors = [
  "Academy Rector",
  "Acquire",
  "Aether Searcher",
  "Agency Outfitter",
  "Ajani's Aid",
  "Alpine Houndmaster",
  "Altar of Bone",
  "Amrou Scout",
  "Anchor to Reality",
  "Angel's Herald",
  "Angrath's Fury",
  "Arachnus Spinner",
  "Arcane Investigator",
  "Archmage Ascension",
  "Arena Rector",
  "Artificer's Intuition",
  "Ashiok, Dream Render",
  "Ashiok's Forerunner",
  "Asmoranomardicadaistinaculdacar",
  "Assembly Hall",
  "Auratouched Mage",
  "Aurochs Herd",
  "Avarax",
  "Ayara's Oathsworn",
  "Basri's Aegis",
  "Battalion Foot Soldier",
  "Begin the Invasion",
  "Behemoth's Herald",
  "Behold the Beyond",
  "Beseech the Mirror",
  "Bifurcate",
  "Bilbo, Birthday Celebrant",
  "Birthing Pod",
  "Bitterheart Witch",
  "Blightspeaker",
  "Blood Speaker",
  "Bogbrew Witch",
  "Boggart Harbinger",
  "Boonweaver Giant",
  "Bribery",
  "Brightglass Gearhulk",
  "Bringer of the Black Dawn",
  "Bring to Light",
  "Brutalizer Exarch",
  "Buried Alive",
  "Burning-Rune Demon",
  "Call the Gatewatch",
  "Captain Sisay",
  "Caradora, Heart of Alacria",
  "Case of the Stashed Skeleton",
  "Cateran Brute",
  "Cateran Enforcer",
  "Cateran Kidnappers",
  "Cateran Overlord",
  "Cateran Persuader",
  "Cateran Summons",
  "Central Elevator // Promising Stairs",
  "Chandra, Heart of Fire",
  "Chandra's Firemaw",
  "Chandra's Flame Wave",
  "Chandra's Outburst",
  "Chord of Calling",
  "Citanul Flute",
  "Clarion Ultimatum",
  "Cloud, Midgar Mercenary",
  "Colossal Rattlewurm",
  "Conduit of Ruin",
  "Conflux",
  "Congregation at Dawn",
  "Corpse Connoisseur",
  "Coveted Prize",
  "Cruel Tutor",
  "Curse of Misfortunes",
  "Cynical Loner",
  "Dark Petition",
  "Dark Supplicant",
  "Daru Cavalier",
  "Deadeye Quartermaster",
  "Deathbellow War Cry",
  "Defense of the Heart",
  "Defiant Falcon",
  "Defiant Vanguard",
  "Demonic Bargain",
  "Demonic Collusion",
  "Demonic Counsel",
  "Demonic Tutor",
  "Demon's Herald",
  "Diabolic Intent",
  "Diabolic Revelation",
  "Diabolic Tutor",
  "Disciples of Gix",
  "Distant Memories",
  "Djeru, With Eyes Open",
  "Domri's Nodorog",
  "Doomsday",
  "Doubling Chant",
  "Dovin's Dismissal",
  "Draconic Muralists",
  "Dragon's Approach",
  "Dragon's Herald",
  "Dragonstorm",
  "Dragonstorm Forecaster",
  "Dwarven Recruiter",
  "Ecological Appreciation",
  "Eerie Procession",
  "Eladamri's Call",
  "Eldritch Evolution",
  "Elspeth's Devotee",
  "Elspeth, Undaunted Hero",
  "Elvish Clancaller",
  "Elvish Harbinger",
  "Embermage Goblin",
  "Emergent Ultimatum",
  "Enduring Ideal",
  "Enigmatic Incarnation",
  "Enlightened Tutor",
  "Entomb",
  "Ethereal Elk",
  "Evolving Door",
  "Eye of Ugin",
  "Fabricate",
  "Faerie Harbinger",
  "Fang-Druid Summoner",
  "Fauna Shaman",
  "Fervent Mastery",
  "Fiend Artisan",
  "Fierce Empath",
  "Fighter Class",
  "Finale of Devastation",
  "Final Parting",
  "Firemind's Foresight",
  "Flamekin Harbinger",
  "Forerunner of the Coalition",
  "Forerunner of the Empire",
  "Forerunner of the Heralds",
  "Forerunner of the Legion",
  "Foresight",
  "Forging the Tyrite Sword",
  "From Beyond",
  "Frostpyre Arcanist",
  "Fugitive of the Judoon",
  "Gamble",
  "Garruk, Caller of Beasts",
  "Garruk Relentless // Garruk, the Veil-Cursed",
  "Garruk's Warsteed",
  "Garruk, Unleashed",
  "Gate to the Afterlife",
  "Gathering Throng",
  "General Tazri",
  "Giant Harbinger",
  "Gideon's Battle Cry",
  "Gideon's Resolve",
  "Gifts Ungiven",
  "Gigantiform",
  "Goblin Engineer",
  "Goblin Matron",
  "Goblin Recruiter",
  "Godo, Bandit Warlord",
  "Goldmane Griffin",
  "Grand Master of Flowers",
  "Grasping Current",
  "Gravebreaker Lamia",
  "Green Sun's Zenith",
  "Grim Servant",
  "Grim Tutor",
  "Grinning Totem",
  "Growth-Chamber Guardian",
  "Grozoth",
  "Guidelight Pathmaker",
  "Heliod's Pilgrim",
  "Hibernation's End",
  "Higure, the Still Wind",
  "Hoarding Broodlord",
  "Hoarding Dragon",
  "Hour of Victory",
  "Howling Wolf",
  "Idyllic Tutor",
  "Ignite the Beacon",
  "Illicit Shipment",
  "Imperial Hellkite",
  "Imperial Recruiter",
  "Imperial Seal",
  "Iname as One",
  "Iname, Death Aspect",
  "Increasing Ambition",
  "Inevitable Betrayal",
  "Infectious Bloodlust",
  "Infernal Tutor",
  "Insatiable Avarice",
  "Insidious Dreams",
  "Instrument of the Bards",
  "Intuition",
  "Invasion of Arcavios // Invocation of the Founders",
  "Invasion of Ikoria // Zilortha, Apex of Ikoria",
  "Invasion of Theros // Ephara, Ever-Sheltering",
  "Invasive Surgery",
  "Inventors' Fair",
  "Invert // Invent",
  "Isperia the Inscrutable",
  "Jace's Ruse",
  "Jarad's Orders",
  "Kaho, Minamo Historian",
  "Kaito Shizuki",
  "Kasmina, Enigma Sage",
  "Kassandra, Eagle Bearer",
  "Kellan, the Fae-Blooded // Birthright Boon",
  "Kithkin Harbinger",
  "Kuldotha Forgemaster",
  "Kyscu Drake",
  "Lagomos, Hand of Hatred",
  "Legion Conquistador",
  "Liberating Combustion",
  "Library of Lat-Nam",
  "Lifespinner",
  "Light-Paws, Emperor's Voice",
  "Liliana's Influence",
  "Liliana's Scorn",
  "Liliana Vess",
  "Lin Sivvi, Defiant Hero",
  "Lively Dirge",
  "Llanowar Sentinel",
  "Long-Term Plans",
  "Lost Auramancers",
  "Lotuslight Dancers",
  "Loyal Inventor",
  "Magda, Brazen Outlaw",
  "Magus of the Order",
  "Mangara's Tome",
  "Manipulate Fate",
  "March of Burgeoning Life",
  "Mask of the Mimic",
  "Mastermind's Acquisition",
  "Mausoleum Secrets",
  "Merchant Scroll",
  "Micromancer",
  "Mimeofacture",
  "Mishra, Artificer Prodigy",
  "Moggcatcher",
  "Momir Vig, Simic Visionary",
  "Moon-Blessed Cleric",
  "Mwonvuli Beast Tracker",
  "Myr Incubator",
  "Myr Kinsmith",
  "Myr Turbine",
  "Mystical Teachings",
  "Mystical Tutor",
  "Mythos of Brokkos",
  "Nahiri, the Harbinger",
  "Natural Order",
  "Nature's Rhythm",
  "Nazahn, Revered Bladesmith",
  "Neoform",
  "Nesting Wurm",
  "Neverending Torment",
  "Niambi, Faithful Healer",
  "Nissa Revane",
  "Oko's Hospitality",
  "Open the Armory",
  "Opposition Agent",
  "Oriq Loremage",
  "Oswald Fiddlebender",
  "Pack Hunt",
  "Panglacial Wurm",
  "Parallel Thoughts",
  "Pattern Matcher",
  "Personal Tutor",
  "Phantom Carriage",
  "Phyrexian Portal",
  "Planar Bridge",
  "Planar Portal",
  "Plea for Guidance",
  "Priest of the Wakening Sun",
  "Primal Command",
  "Prime Speaker Vannifar",
  "Profane Tutor",
  "Protean Hulk",
  "Pyre of Heroes",
  "Quest for the Holy Relic",
  "Ral's Dispersal",
  "Ramosian Captain",
  "Ramosian Commander",
  "Ramosian Lieutenant",
  "Ramosian Sergeant",
  "Ramosian Sky Marshal",
  "Ranger-Captain of Eos",
  "Ranger of Eos",
  "Ratcatcher",
  "Rathi Assassin",
  "Rathi Fiend",
  "Rathi Intimidator",
  "Raven Clan War-Axe",
  "Razaketh's Rite",
  "Razaketh, the Foulblooded",
  "Reckless Handling",
  "Recruiter of the Guard",
  "Relic Seeker",
  "Remembrance",
  "Renowned Weaponsmith",
  "Repurposing Bay",
  "Reshape",
  "Rhystic Tutor",
  "Rhythmic Water Vortex",
  "Ring of Three Wishes",
  "Ringsight",
  "River Song",
  "Rocco, Cabaretti Caterer",
  "Rootless Yew",
  "Rowan's Stalwarts",
  "Runed Crown",
  "Runeforge Champion",
  "Rune-Scarred Demon",
  "Rushed Rebirth",
  "Saheeli Rai",
  "Samut, the Tested",
  "Sanctum of All",
  "Sarkhan, Dragonsoul",
  "Sarkhan's Triumph",
  "Sarkhan Unbroken",
  "Scion of the Ur-Dragon",
  "Scrapyard Recombiner",
  "Screaming Seahawk",
  "Seahunter",
  "Search for Glory",
  "Secret Summoning",
  "Self-Assembler",
  "Servant of the Stinger",
  "Shadowborn Apostle",
  "Shadow-Rite Priest",
  "Shared Summons",
  "Shaun & Rebecca, Agents",
  "Shield-Wall Sentinel",
  "Shrine Steward",
  "Sidisi, Undead Vizier",
  "Sift Through Sands",
  "Signal the Clans",
  "Sisay, Weatherlight Captain",
  "Sivitri, Dragon Master",
  "Skyship Weatherlight",
  "Skyshroud Poacher",
  "Skyshroud Sentinel",
  "Sliver Overlord",
  "Smuggler Captain",
  "Solve the Equation",
  "Sorin's Guide",
  "Sovereigns of Lost Alara",
  "Spellseeker",
  "Sphinx Ambassador",
  "Sphinx's Herald",
  "Sphinx Summoner",
  "Squadron Hawk",
  "Steelshaper Apprentice",
  "Steelshaper's Gift",
  "Sterling Grove",
  "Stoneforge Mystic",
  "Stonehewer Giant",
  "Summoner's Bond",
  "Summoner's Pact",
  "Sun-Blessed Mount",
  "Sunforger",
  "Supply // Demand",
  "Survival of the Fittest",
  "Sylvan Tutor",
  "Taj-Nar Swordsmith",
  "Tallowisp",
  "Tamiyo's Journal",
  "Teferi's Wavecaster",
  "Tempest Hawk",
  "Templar Knight",
  "Tezzeret, Artifice Master",
  "Tezzeret's Betrayal",
  "Tezzeret the Seeker",
  "Thalia's Lancers",
  "The Caves of Androzani",
  "The Creation of Avacyn",
  "The Cruelty of Gix",
  "The Eleventh Hour",
  "The End",
  "The First Doctor",
  "The Five Doctors",
  "The Hunger Tide Rises",
  "Thornvault Forager",
  "Threats Undetected",
  "Three Dreams",
  "Tiamat",
  "Time of Need",
  "Tinker",
  "Tooth and Nail",
  "Totem-Guide Hartebeest",
  "Tower Winder",
  "Transit Mage",
  "Transmutation Font",
  "Transmute Artifact",
  "Trapmaker's Snare",
  "Treasure Chest",
  "Treasure Mage",
  "Tribute Mage",
  "Trinket Mage",
  "Trophy Mage",
  "Trustworthy Scout",
  "Twice Upon a Time // Unlikely Meeting",
  "Uncage the Menagerie",
  "Unmarked Grave",
  "Urborg Panther",
  "Urza's Saga",
  "Vampiric Tutor",
  "Vexing Puzzlebox",
  "Vile Entomber",
  "Visage of Bolas",
  "Vivien, Monsters' Advocate",
  "Vivien on the Hunt",
  "Vizier of the Anointed",
  "Vraska's Scorn",
  "Vraska's Stoneglare",
  "Wargate",
  "War of the Last Alliance",
  "Welkin Hawk",
  "Whir of Invention",
  "Whisper Squad",
  "Wild Pair",
  "Wild Research",
  "Wirewood Herald",
  "Wishclaw Talisman",
  "Woodland Bellower",
  "Worldly Tutor",
  "Wretched Throng",
  "Yanling's Harbinger",
  "Yisan, the Wanderer Bard",
  "Zirilan of the Claw",
  "Zur the Enchanter",
];

export const MassLandDenial = [
  "Acid Rain",
  "Alpine Moon",
  "Apocalypse",
  "Armageddon",
  "Back to Basics",
  "Bearer of the Heavens",
  "Bend or Break",
  "Blood Moon",
  "Boil",
  "Boiling Seas",
  "Boom // Bust",
  "Burning of Xinye",
  "Cataclysm",
  "Catastrophe",
  "Cleansing",
  "Contamination",
  "Conversion",
  "Death Cloud",
  "Decree of Annihilation",
  "Desolation Angel",
  "Destructive Force",
  "Devastating Dreams",
  "Devastation",
  "Dimensional Breach",
  "Epicenter",
  "Fall of the Thran",
  "Flashfires",
  "Gilt-Leaf Archdruid",
  "Glaciers",
  "Global Ruin",
  "Hall of Gemstone",
  "Harbinger of the Seas",
  "Hokori, Dust Drinker",
  "Impending Disaster",
  "Infernal Darkness",
  "Jokulhaups",
  "Keldon Firebombers",
  "Magus of the Moon",
  "Myojin of Infinite Rage",
  "Naked Singularity",
  "Obliterate",
  "Omen of Fire",
  "Raiding Party",
  "Ravages of War",
  "Razia's Purification",
  "Reality Twist",
  "Realm Razer",
  "Rising Waters",
  "Ritual of Subdual",
  "Ruination",
  "Soulscour",
  "Stasis",
  "Static Orb",
  "Stench of Evil",
  "Sunder",
  "Tectonic Break",
  "Thoughts of Ruin",
  "Tsunami",
  "Urza's Sylex",
  "Wildfire",
  "Winter Moon",
  "Winter Orb",
  "Worldfire",
  "Worldpurge",
  "Worldslayer",
];

export const ExtraTurnsSearch = `o:"take" and o:"extra" and o:"turn" and game:"paper" and border:"black"`;

export const ExtraTurns = [
  "Alchemist's Gambit",
  "Alrund's Epiphany",
  "Beacon of Tomorrows",
  "Capture of Jingzhou",
  "Chance for Glory",
  "Eon Frolicker",
  "Expropriate",
  "Final Fortune",
  "Gonti's Aether Heart",
  "Ichormoon Gauntlet",
  "Karn's Temporal Sundering",
  "Last Chance",
  "Lighthouse Chronologist",
  "Lost Isle Calling",
  "Magistrate's Scepter",
  "Magosi, the Waterveil",
  "Medomai the Ageless",
  "Mu Yanling",
  "Nexus of Fate",
  "Notorious Throng",
  "Part the Waterveil",
  "Plea for Power",
  "Ral Zarek",
  "Regenerations Restored",
  "Rise of the Eldrazi",
  "Sage of Hours",
  "Savor the Moment",
  "Search the City",
  "Second Chance",
  "Seedtime",
  "Stitch in Time",
  "Teferi, Master of Time",
  "Teferi, Timebender",
  "Temporal Extortion",
  "Temporal Manipulation",
  "Temporal Mastery",
  "Temporal Trespass",
  "Time Sieve",
  "Timesifter",
  "Timestream Navigator",
  "Time Stretch",
  "Time Vault",
  "Time Walk",
  "Time Warp",
  "Twice Upon a Time // Unlikely Meeting",
  "Ugin's Nexus",
  "Ultimecia, Time Sorceress // Ultimecia, Omnipotent",
  "Walk the Aeons",
  "Wanderwine Prophets",
  "Warrior's Oath",
  "Wormfang Manta",
];
